export const selectField = [
    { value: 'Computer Science', label: 'Computer Science' },
    { value: 'Engineering', label: 'Engineering' },
    { value: 'Architecture', label: 'Architecture' },
    { value: 'Mathematics', label: 'Mathematics' },
    { value: 'Biology', label: 'Biology' },
    { value: 'Chemistry', label: 'Chemistry' },
    { value: 'Physics', label: 'Physics' },
    { value: 'Economics', label: 'Economics' },
    { value: 'Psychology', label: 'Psychology' },
    { value: 'Sociology', label: 'Sociology' },
    { value: 'Philosophy', label: 'Philosophy' },
    { value: 'Political Science', label: 'Political Science' },
    { value: 'History', label: 'History' },
    { value: 'Literature', label: 'Literature' },
    { value: 'Business Administration', label: 'Business Administration' },
    { value: 'Finance', label: 'Finance' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Management', label: 'Management' },
    { value: 'Human Resources', label: 'Human Resources' },
    { value: 'Accounting', label: 'Accounting' },
    { value: 'Public Administration', label: 'Public Administration' },
    { value: 'Healthcare Administration', label: 'Healthcare Administration' },
    { value: 'Nursing', label: 'Nursing' },
    { value: 'Medicine', label: 'Medicine' },
    { value: 'Dentistry', label: 'Dentistry' },
    { value: 'Pharmacy', label: 'Pharmacy' },
    { value: 'Physical Therapy', label: 'Physical Therapy' },
    { value: 'Occupational Therapy', label: 'Occupational Therapy' },
    { value: 'Veterinary Medicine', label: 'Veterinary Medicine' },
    { value: 'Law', label: 'Law' },
    { value: 'Criminal Justice', label: 'Criminal Justice' },
    { value: 'Forensic Science', label: 'Forensic Science' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'Data Science', label: 'Data Science' },
    { value: 'Information Technology', label: 'Information Technology' },
    { value: 'Software Engineering', label: 'Software Engineering' },
    { value: 'Network Engineering', label: 'Network Engineering' },
    { value: 'Web Development', label: 'Web Development' },
    { value: 'Graphic Design', label: 'Graphic Design' },
    { value: 'Interior Design', label: 'Interior Design' },
    { value: 'Fashion Design', label: 'Fashion Design' },
    { value: 'Fine Arts', label: 'Fine Arts' },
    { value: 'Music', label: 'Music' },
    { value: 'Film Studies', label: 'Film Studies' },
    { value: 'Theater', label: 'Theater' },
    { value: 'Dance', label: 'Dance' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Journalism', label: 'Journalism' },
    { value: 'Communication', label: 'Communication' },
    { value: 'Media Studies', label: 'Media Studies' },
    { value: 'Public Relations', label: 'Public Relations' },
    { value: 'Advertising', label: 'Advertising' },
    { value: 'Education', label: 'Education' },
    { value: 'Early Childhood Education', label: 'Early Childhood Education' },
    { value: 'Elementary Education', label: 'Elementary Education' },
    { value: 'Secondary Education', label: 'Secondary Education' },
    { value: 'Special Education', label: 'Special Education' },
    { value: 'Curriculum and Instruction', label: 'Curriculum and Instruction' },
    { value: 'Educational Leadership', label: 'Educational Leadership' },
    { value: 'School Counseling', label: 'School Counseling' },
    { value: 'Higher Education Administration', label: 'Higher Education Administration' },
    { value: 'Library Science', label: 'Library Science' },
    { value: 'Environmental Science', label: 'Environmental Science' },
    { value: 'Geology', label: 'Geology' },
    { value: 'Meteorology', label: 'Meteorology' },
    { value: 'Astronomy', label: 'Astronomy' },
    { value: 'Oceanography', label: 'Oceanography' },
    { value: 'Geography', label: 'Geography' },
    { value: 'Environmental Studies', label: 'Environmental Studies' },
    { value: 'Ecology', label: 'Ecology' },
    { value: 'Conservation Biology', label: 'Conservation Biology' },
    { value: 'Marine Biology', label: 'Marine Biology' },
    { value: 'Zoology', label: 'Zoology' },
    { value: 'Botany', label: 'Botany' },
    { value: 'Genetics', label: 'Genetics' },
    { value: 'Cell Biology', label: 'Cell Biology' },
    { value: 'Microbiology', label: 'Microbiology' },
    { value: 'Biochemistry', label: 'Biochemistry' },
    { value: 'Biotechnology', label: 'Biotechnology' },
    { value: 'Immunology', label: 'Immunology' },
    { value: 'Neuroscience', label: 'Neuroscience' },
    { value: 'Biophysics', label: 'Biophysics' },
    { value: 'Biomedical Engineering', label: 'Biomedical Engineering' },
    { value: 'Bioinformatics', label: 'Bioinformatics' },
    { value: 'Biostatistics', label: 'Biostatistics' },
    { value: 'Public Health', label: 'Public Health' },
    { value: 'Epidemiology', label: 'Epidemiology' },
    { value: 'Health Policy', label: 'Health Policy' },
    { value: 'Health Informatics', label: 'Health Informatics' },
    { value: 'Health Services Administration', label: 'Health Services Administration' },
    { value: 'Health Education', label: 'Health Education' },
    { value: 'Nutrition', label: 'Nutrition' },
    { value: 'Exercise Science', label: 'Exercise Science' },
    { value: 'Kinesiology', label: 'Kinesiology' },
    { value: 'Sports Management', label: 'Sports Management' },
    { value: 'Physical Education', label: 'Physical Education' },
    { value: 'Recreation Management', label: 'Recreation Management' },
    { value: 'Leisure Studies', label: 'Leisure Studies' },
]  