export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"

export const GET_FROM_CART_REQUEST = "GET_FROM_CART_REQUEST"
export const GET_FROM_CART_SUCCESS = "GET_FROM_CART_SUCCESS"
export const GET_FROM_CART_FAIL = "GET_FROM_CART_FAIL"

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL"


export const ADD_TO_WISH_LIST_REQUEST = "ADD_TO_WISH_LIST_REQUEST"
export const ADD_TO_WISH_LIST_SUCCESS = "ADD_TO_WISH_LIST_SUCCESS"
export const ADD_TO_WISH_LIST_FAIL = "ADD_TO_WISH_LIST_FAIL"

export const GET_FROM_WISH_LIST_REQUEST = "GET_FROM_WISH_LIST_REQUEST"
export const GET_FROM_WISH_LIST_SUCCESS = "GET_FROM_WISH_LIST_SUCCESS"
export const GET_FROM_WISH_LIST_FAIL = "GET_FROM_WISH_LIST_FAIL"

export const REMOVE_FROM_WISH_LIST_REQUEST = "REMOVE_FROM_WISH_LIST_REQUEST"
export const REMOVE_FROM_WISH_LIST_SUCCESS = "REMOVE_FROM_WISH_LIST_SUCCESS"
export const REMOVE_FROM_WISH_LIST_FAIL = "REMOVE_FROM_WISH_LIST_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"