export const CREATE_COURSES_REQUEST = "CREATE_COURSES_REQUEST"
export const CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS"
export const CREATE_COURSES_FAIL = "CREATE_COURSES_FAIL"

export const GET_ALL_ADMIN_COURSES_REQUEST = "GET_ALL_ADMIN_COURSES_REQUEST"
export const GET_ALL_ADMIN_COURSES_SUCCESS = "GET_ALL_ADMIN_COURSES_SUCCESS"
export const GET_ALL_ADMIN_COURSES_FAIL = "GET_ALL_ADMIN_COURSES_FAIL"



export const CLEAR_ERRORS = "CLEAR_ERRORS"