export const CREATE_COURSES_REQUEST = "CREATE_COURSES_REQUEST"
export const CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS"
export const CREATE_COURSES_FAIL = "CREATE_COURSES_FAIL"

export const GET_ALL_ADMIN_COURSES_REQUEST = "GET_ALL_ADMIN_COURSES_REQUEST"
export const GET_ALL_ADMIN_COURSES_SUCCESS = "GET_ALL_ADMIN_COURSES_SUCCESS"
export const GET_ALL_ADMIN_COURSES_FAIL = "GET_ALL_ADMIN_COURSES_FAIL"

export const GET_SINGLE_ADMIN_COURSES_REQUEST = "GET_SINGLE_ADMIN_COURSES_REQUEST"
export const GET_SINGLE_ADMIN_COURSES_SUCCESS = "GET_SINGLE_ADMIN_COURSES_SUCCESS"
export const GET_SINGLE_ADMIN_COURSES_FAIL = "GET_SINGLE_ADMIN_COURSES_FAIL"

export const UPDATE_ADMIN_COURSES_REQUEST = "UPDATE_ADMIN_COURSES_REQUEST"
export const UPDATE_ADMIN_COURSES_SUCCESS = "UPDATE_ADMIN_COURSES_SUCCESS"
export const UPDATE_ADMIN_COURSES_FAIL = "UPDATE_ADMIN_COURSES_FAIL"

export const DELETE_ADMIN_COURSES_REQUEST = "DELETE_ADMIN_COURSES_REQUEST"
export const DELETE_ADMIN_COURSES_SUCCESS = "DELETE_ADMIN_COURSES_SUCCESS"
export const DELETE_ADMIN_COURSES_FAIL = "DELETE_ADMIN_COURSES_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"