export const CREATE_COURSES_REQUEST = "CREATE_COURSES_REQUEST"
export const CREATE_COURSES_SUCCESS = "CREATE_COURSES_SUCCESS"
export const CREATE_COURSES_FAIL = "CREATE_COURSES_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"