export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST"
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS"
export const CREATE_JOB_FAIL = "CREATE_JOB_FAIL"

export const UPDATE_JOB_REQUEST = "UPDATE_JOB_REQUEST"
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS"
export const UPDATE_JOB_FAIL = "UPDATE_JOB_FAIL"

export const GET_ALL_HR_JOB_REQUEST = "GET_ALL_HR_JOB_REQUEST"
export const GET_ALL_HR_JOB_SUCCESS = "GET_ALL_HR_JOB_SUCCESS"
export const GET_ALL_HR_JOB_FAIL = "GET_ALL_HR_JOB_FAIL"

export const GET_SINGLE_HR_JOB_REQUEST = "GET_SINGLE_HR_JOB_REQUEST"
export const GET_SINGLE_HR_JOB_SUCCESS = "GET_SINGLE_HR_JOB_SUCCESS"
export const GET_SINGLE_HR_JOB_FAIL = "GET_SINGLE_HR_JOB_FAIL"

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST"
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS"
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL"


export const GET_ALL_PUBLIC_JOB_REQUEST = "GET_ALL_PUBLIC_JOB_REQUEST"
export const GET_ALL_PUBLIC_JOB_SUCCESS = "GET_ALL_PUBLIC_JOB_SUCCESS"
export const GET_ALL_PUBLIC_JOB_FAIL = "GET_ALL_PUBLIC_JOB_FAIL"

export const GET_SINGLE_PUBLIC_JOB_REQUEST = "GET_SINGLE_PUBLIC_JOB_REQUEST"
export const GET_SINGLE_PUBLIC_JOB_SUCCESS = "GET_SINGLE_PUBLIC_JOB_SUCCESS"
export const GET_SINGLE_PUBLIC_JOB_FAIL = "GET_SINGLE_PUBLIC_JOB_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"