export const GET_MY_PROFILE_REQUEST = "GET_MY_PROFILE_REQUEST"
export const GET_MY_PROFILE_SUCCESS = "GET_MY_PROFILE_SUCCESS"
export const GET_MY_PROFILE_FAIL = "GET_MY_PROFILE_FAIL"

export const UPDATE_MY_PROFILE_REQUEST = "UPDATE_MY_PROFILE_REQUEST"
export const UPDATE_MY_PROFILE_SUCCESS = "UPDATE_MY_PROFILE_SUCCESS"
export const UPDATE_MY_PROFILE_FAIL = "UPDATE_MY_PROFILE_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"