export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED"

export const GET_ALL_USERS_ADMIN_REQUEST = "GET_ALL_USERS_ADMIN_REQUEST"
export const GET_ALL_USERS_ADMIN_SUCCESS = "GET_ALL_USERS_ADMIN_SUCCESS"
export const GET_ALL_USERS_ADMIN_FAIL = "GET_ALL_USERS_ADMIN_FAIL"

export const CREATE_NEW_USER_ADMIN_REQUEST = "CREATE_NEW_USER_ADMIN_REQUEST"
export const CREATE_NEW_USER_ADMIN_SUCCESS = "CREATE_NEW_USER_ADMIN_SUCCESS"
export const CREATE_NEW_USER_ADMIN_FAIL = "CREATE_NEW_USER_ADMIN_FAIL"

export const UPDATE_USER_ADMIN_REQUEST = "UPDATE_USER_ADMIN_REQUEST"
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS"
export const UPDATE_USER_ADMIN_FAIL = "UPDATE_USER_ADMIN_FAIL"

export const DELETE_USER_ADMIN_REQUEST = "DELETE_USER_ADMIN_REQUEST"
export const DELETE_USER_ADMIN_SUCCESS = "DELETE_USER_ADMIN_SUCCESS"
export const DELETE_USER_ADMIN_FAIL = "DELETE_USER_ADMIN_FAIL"

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST"
export const FORGET_PASSWORD_SUCESS = "FORGET_PASSWORD_SUCESS"
export const FORGET_PASSWORD_FAIL = "FORGET_PASSWORD_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"